"""
available choices for 
"mo_optimizer" = "linear_scalarization" | "uhv" (not tested) | "higamo_hv" | "pareto_mtl" | "epo"
"mo_mode" = "mean_loss_over_samples" | "loss_per_sample"
"mo_optimizer_params" = {"weights": n_obj * n_sol, default None} 		for "linear_scalarization",
						{"ud_eps": 10e-5} 		for "uhv",
						{"preferences": n_sol * n_obj, default None} 	for "pareto_mtl" and "epo",
						{"eps": float, default 1e-4} for "epo",

"""

default_config = {"modir":	{"problem_name": "modir",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "MNIST_DIR",
	"data_params": {"n_samples": 10000, "root": "/export/scratch3/grewal/Data/"},
	"train_ratio": 0.8,
	"network": "Net",
	"network_params": {"width":16, "depth":3},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"weight_decay": 1e-4, "lr": 1e-3},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
	"batch_size": 8,
	"n_learning_iterations": 20000,
	"obj_func": ["NCCLoss", "TransformationLoss"],
	"ref_point": [20, 20]
		},

	"sin_cos_3d": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 400, "use_three_losses": True, "cycles": 1, "scales": (1, 1, 1), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-3, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 30000,
	"obj_func": ["cos_MSELoss", "sin_MSELoss", "shifted_sin_MSELoss"],
	"ref_point": [20, 20, 20]
		},

	"sin_cos": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 400, "use_three_losses": False, "cycles": 1, "scales": (1, 1), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-3, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 20000,
	"obj_func": ["cos_MSELoss", "sin_MSELoss"],
	"ref_point": [20, 20]
		},

	"sin_cos_doublesqrt": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "loss_per_sample",
	"n_mo_sol": 10,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 40, "use_three_losses": False, "cycles": 1, "scales": (1, 1), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-3, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 20,
	"n_learning_iterations": 40000,
	"obj_func": ["cos_sqrtLoss", "sin_sqrtLoss"],
	"ref_point": [20, 20]
		},


	"sin_cos_scaledmse": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 400, "use_three_losses": False, "cycles": 1, "scales": (1, 1), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-3, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 20000,
	"obj_func": ["cos_scaledMSELoss", "sin_MSELoss"],
	"ref_point": [20, 20]
		},

	"sin_cos_l1": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 400, "use_three_losses": False, "cycles": 1, "scales": (1, 1), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-3, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 20000,
	"obj_func": ["cos_L1Loss", "sin_MSELoss"],
	"ref_point": [20, 20]
		},

	"sin_cos_scaled": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 400, "use_three_losses": False, "cycles": 1, "scales": (1, 0.01), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-1, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 20000,
	"obj_func": ["cos_MSELoss", "sin_MSELoss"],
	"ref_point": [20, 20]
		},

	"sin_cos_l1scaled": {"problem_name": "sin_cos",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "TrigonometryDataset",
	"data_params": {"n_samples": 400, "use_three_losses": False, "cycles": 1, "scales": (1, 0.01), "std_noise": 0},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"n_intermediate_layers": 2},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-1, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 20000,
	"obj_func": ["cos_L1Loss", "sin_MSELoss"],
	"ref_point": [20, 20]
		},

	"linear_regression": {"problem_name": "linear_regression",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 4,
	"dataset": "LinearRegressionDataset",
	"train_ratio": 0.8,
	"data_params": {"n_samples": 10000},
	"network": "Net",
	"network_params": {},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-1},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
	"batch_size": 100,
	"n_learning_iterations": 10000,
	"obj_func": ["MSELoss", "SparsityLoss"],
	"ref_point": [1000, 100]
		},

	"pruning-toy": {"problem_name": "pruning",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 4,
	"dataset": "ToyRegressionDataset",
	"data_params": {"n_samples": 10000},
	"train_ratio": 0.8,
	"network": "ToyNet",
	"network_params": {},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-2},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
	"batch_size": 100,
	"n_epochs": 25,
	"n_learning_iterations": 10000,
	"obj_func": ["MSELoss", "L1Loss"],
	"ref_point": [50, 1000]
		},

	"pruning-resnet18-cifar10": {"problem_name": "pruning",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 4,
	"dataset": "CIFAR10",
	"data_params": {"n_samples": 50000, "root": "/export/scratch2/virgolin/datasets_pruning/"},
	"train_ratio": 1.0,
	"network": "ResNet-18",
	"network_params": {},
	"meta_optimizer_name": "SGD",
	"meta_optimizer_params": {"lr": 0.01},
	"meta_optimizer_scheduler_name": "MultiStepLR",
	"meta_optimizer_scheduler_params": {"milestones": [60, 120],"gamma": 0.1},
	"batch_size": 128,
	"n_epochs": 160,
	"n_learning_iterations": 10000,
	"obj_func": ["CrossEntropyLoss", "L1Loss"],
	"ref_point": [100, 1000]
		},

	"fashion_mnist": {"problem_name": "fashion_mnist",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 4,
	"dataset": "CustomDataset",
	"data_params": {"n_samples": 10000, "root": ""},
	"train_ratio": 0.8,
	"network": "Net",
	"network_params": {},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"weight_decay": 1e-4, "lr": 1e-3},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
	"batch_size": 1000,
	"n_learning_iterations": 10000,
	"obj_func": ["MSELoss", "MSELoss"],
	"ref_point": [0.5, 0.5]
		},
	
	"vincent_van_jarjar_3D": {"problem_name": "vincent_van_jarjar",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 6,
	"dataset": "VincentVanJarJarDataset",
	"data_params": {"n_samples": 5},
	"train_ratio": 0.8,
	"network": "Net",
	"network_params": {"set_nr": 1},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-2,"betas": (0.99,0.999)},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
	"batch_size": 1,
	"n_learning_iterations": 2500,
	"obj_func": ["StyleLoss","StyleLoss","StyleLoss"],
	"ref_point": [10,10,10]
		},

	"vincent_van_jarjar_2D": {"problem_name": "vincent_van_jarjar",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 6,
	"dataset": "VincentVanJarJarDataset",
	"data_params": {"n_samples": 5},
	"train_ratio": 0.8,
	"network": "Net",
	"network_params": {"set_nr": 101},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-2,"betas": (0.99,0.999)},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
	"batch_size": 1,
	"n_learning_iterations": 2500,
	"obj_func": ["StyleLoss","ContentLoss"],
	"ref_point": [1e-1,1e3]
		},

	"mtl_as_moo": {"problem_name": "mtl_as_moo",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "MultiMNIST",
	"data_params": {"n_samples": 120000, "root": "/export/scratch3/grewal/Data/MultiMNIST",
					 "filename": "multi_mnist.pickle", "task": "both"},
	"train_ratio": 1.0,
	"network": "LeNet",
	"network_params": {"n_tasks":2},
	"meta_optimizer_name": "SGD",
	"meta_optimizer_params": {"lr":1e-3, "momentum":0.9},
	"meta_optimizer_scheduler_name": "MultiStepLR",
	"meta_optimizer_scheduler_params": {"milestones":[7020,14040,21060,28080,35100,42120], "gamma":0.5},
	"batch_size": 256,
	"n_learning_iterations": 46800,
	"obj_func": ["CrossEntropyLoss", "CrossEntropyLoss"],
	"ref_point": [20, 20]
		},

	"mo_segmentation": {"problem_name": "mo_segmentation",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "ProstateDataset",
	"data_params": {"n_samples":579, "root": "/export/scratch3/grewal/Data/ProstateDataset/datainfo.csv",
					"styles": ["with_dilation_5", "with_erosion_5"]},
	"train_ratio": 0.8,
	"network": "UNet",
	"network_params": {"width":64, "batchnorm":True},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-4, "weight_decay": 1e-4},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 2000, "gamma": 1.0},
	"batch_size": 4,
	"n_learning_iterations": 6000,
	"obj_func": ["SoftDiceLoss", "SoftDiceLoss"],
	"ref_point": [1, 1]
		},

	"synthetic_concave": {"problem_name": "synthetic_concave",
	"mo_optimizer": "higamo_hv",
	"mo_optimizer_params": {"beta_one": 0.9, "obj_space_normalize": True},
	"mo_mode": "mean_loss_over_samples",
	"n_mo_sol": 5,
	"dataset": "ConstantDataset",
	"data_params": {"n_samples": 400, "ndim": 1},
	"train_ratio": 0.5,
	"network": "Net",
	"network_params": {"ndim": 1},
	"meta_optimizer_name": "Adam",
	"meta_optimizer_params": {"lr": 1e-3, "betas": [0.99,0.999]},
	"meta_optimizer_scheduler_name": "StepLR",
	"meta_optimizer_scheduler_params": {"step_size": 1, "gamma": 1.0},
	"batch_size": 200,
	"n_learning_iterations": 2000,
	"obj_func": ["Loss1", "Loss2"],
	"ref_point": [10, 10]
		},

	"modir_amc":	{"problem_name": "modir3d",
		"mo_optimizer": "higamo_hv",
		"mo_optimizer_params": {"beta_one": 0, "obj_space_normalize": True},
		"mo_mode": "mean_loss_over_samples",
		"n_mo_sol": 5,
		"dataset": "MODIR_Dataset",
		"data_params": {"n_samples": 100, "root": "/export/scratch3/grewal/Data/Projects_JPG_data/MO_DIR/CT/MODIR_data_train_split"},
		"train_ratio": 0.8,
		"network": "Net",
		"network_params": {"width":16, "depth":4, "threeD":True},
		"meta_optimizer_name": "Adam",
		"meta_optimizer_params": {"weight_decay": 1e-4, "lr": 1e-3},
		"meta_optimizer_scheduler_name": "StepLR",
		"meta_optimizer_scheduler_params": {"step_size": 1,"gamma": 1.0},
		"batch_size": 1,
		"n_learning_iterations": 10000,
		"obj_func": ["NCCLoss", "TransformationLoss"],
		"ref_point": [20, 20]
			},
}
